services:
  - type: web
    name: polaris-backend
    plan: free 
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000